#!/bin/bash
# Generates ~/.claude/CLAUDE.md with hardware context that Claude can't easily discover

MD="/home/claude/.claude/CLAUDE.md"

# GPU info
GPU_NAME=$(nvidia-smi --query-gpu=name --format=csv,noheader 2>/dev/null | head -1 || echo "unknown")
GPU_VRAM_MB=$(nvidia-smi --query-gpu=memory.total --format=csv,noheader,nounits 2>/dev/null | head -1 || echo "0")
GPU_VRAM_GB=$(awk "BEGIN {printf \"%.0f\", ${GPU_VRAM_MB}/1024}")
GPU_COUNT=$(nvidia-smi --query-gpu=name --format=csv,noheader 2>/dev/null | wc -l || echo "1")

# CUDA compute capability
COMPUTE_CAP=$(nvidia-smi --query-gpu=compute_cap --format=csv,noheader 2>/dev/null | head -1 || echo "unknown")
SM_CODE="sm_$(echo "$COMPUTE_CAP" | tr -d '.')"

ARCH_NAME="unknown"
case "$SM_CODE" in
  sm_70) ARCH_NAME="Volta" ;;
  sm_75) ARCH_NAME="Turing" ;;
  sm_80|sm_86) ARCH_NAME="Ampere" ;;
  sm_89) ARCH_NAME="Ada Lovelace" ;;
  sm_90) ARCH_NAME="Hopper" ;;
  sm_100|sm_103) ARCH_NAME="Blackwell" ;;
  sm_120) ARCH_NAME="Blackwell Ultra" ;;
esac

# Inference backend compatibility
VLLM_STATUS="Yes"
VLLM_NOTE=""
SGLANG_STATUS="Yes"
SGLANG_NOTE=""
SM_NUM=$(echo "$COMPUTE_CAP" | tr -d '.')

if [ "$SM_NUM" -ge 120 ] 2>/dev/null; then
  VLLM_STATUS="No — vLLM does not support ${ARCH_NAME} (${SM_CODE}) yet"
  SGLANG_NOTE=" (requires --attention-backend triton)"
elif [ "$SM_NUM" -ge 100 ] 2>/dev/null; then
  VLLM_NOTE=" (Blackwell support may be experimental)"
  SGLANG_NOTE=" (requires --attention-backend triton)"
fi

# Model size limits (rough, single GPU, ~2GB overhead)
BF16_MAX=$(awk "BEGIN {v=(${GPU_VRAM_MB}-2048)/2/1024; printf \"%.0f\", (v<0)?0:v}")
INT8_MAX=$(awk "BEGIN {v=(${GPU_VRAM_MB}-2048)/1/1024; printf \"%.0f\", (v<0)?0:v}")
INT4_MAX=$(awk "BEGIN {v=(${GPU_VRAM_MB}-2048)/0.5/1024; printf \"%.0f\", (v<0)?0:v}")

# HF_TOKEN status
HF_STATUS="NOT SET — gated model downloads will fail"
if [ -n "${HF_TOKEN:-}" ] || [ -n "${HUGGING_FACE_HUB_TOKEN:-}" ]; then
  HF_STATUS="Set"
fi

cat > "$MD" << MDEOF
# Machine Context — auto-generated by claude-init

## Hardware

- GPU: ${GPU_COUNT}x ${GPU_NAME} (${GPU_VRAM_GB} GB VRAM each)
- CUDA compute capability: ${COMPUTE_CAP} (${SM_CODE}, ${ARCH_NAME})

## Inference backends

- vLLM: ${VLLM_STATUS}${VLLM_NOTE}
- SGLang: ${SGLANG_STATUS}${SGLANG_NOTE}
- Transformers: Always works

## Model size limits (approximate, single GPU)

- bf16: ~${BF16_MAX}B parameters
- int8: ~${INT8_MAX}B parameters
- int4: ~${INT4_MAX}B parameters

Multi-GPU with tensor parallelism multiplies these by GPU count (${GPU_COUNT}).

## Storage conventions

- Models: /workspace/models/
- Data: /workspace/data/
- HF cache: /workspace/.cache/huggingface/
- HF_TOKEN: ${HF_STATUS}

## Package installation

Use: uv pip install --system --compile-bytecode --break-system-packages -e .
Do NOT pin or reinstall torch, torchvision, torchaudio, or CUDA — they come from the base image.
MDEOF

chown claude:claude "$MD"