#!/bin/bash
# Generates ~/.claude/CLAUDE.md with hardware context that Claude can't easily discover

MD="/root/.claude/CLAUDE.md"

# GPU info
GPU_NAME=$(nvidia-smi --query-gpu=name --format=csv,noheader 2>/dev/null | head -1 || echo "unknown")
GPU_VRAM_MB=$(nvidia-smi --query-gpu=memory.total --format=csv,noheader,nounits 2>/dev/null | head -1 || echo "0")
GPU_VRAM_GB=$(awk "BEGIN {printf \"%.0f\", ${GPU_VRAM_MB}/1024}")
GPU_COUNT=$(nvidia-smi --query-gpu=name --format=csv,noheader 2>/dev/null | wc -l || echo "1")

# CUDA compute capability
COMPUTE_CAP=$(nvidia-smi --query-gpu=compute_cap --format=csv,noheader 2>/dev/null | head -1 || echo "unknown")
SM_CODE="sm_$(echo "$COMPUTE_CAP" | tr -d '.')"

ARCH_NAME="unknown"
case "$SM_CODE" in
  sm_70) ARCH_NAME="Volta" ;;
  sm_75) ARCH_NAME="Turing" ;;
  sm_80|sm_86) ARCH_NAME="Ampere" ;;
  sm_89) ARCH_NAME="Ada Lovelace" ;;
  sm_90) ARCH_NAME="Hopper" ;;
  sm_100|sm_103) ARCH_NAME="Blackwell" ;;
  sm_120) ARCH_NAME="Blackwell Ultra" ;;
esac

# Inference backend compatibility
VLLM_STATUS="Yes"
VLLM_NOTE=""
SGLANG_STATUS="Yes"
SGLANG_NOTE=""
SM_NUM=$(echo "$COMPUTE_CAP" | tr -d '.')

if [ "$SM_NUM" -ge 120 ] 2>/dev/null; then
  VLLM_STATUS="No — vLLM does not support ${ARCH_NAME} (${SM_CODE}) yet"
  SGLANG_NOTE=" (requires --attention-backend triton)"
elif [ "$SM_NUM" -ge 100 ] 2>/dev/null; then
  VLLM_NOTE=" (Blackwell support may be experimental)"
  SGLANG_NOTE=" (requires --attention-backend triton)"
fi

# Model size limits (rough, single GPU, ~2GB overhead)
BF16_MAX=$(awk "BEGIN {v=(${GPU_VRAM_MB}-2048)/2/1024; printf \"%.0f\", (v<0)?0:v}")
INT8_MAX=$(awk "BEGIN {v=(${GPU_VRAM_MB}-2048)/1/1024; printf \"%.0f\", (v<0)?0:v}")
INT4_MAX=$(awk "BEGIN {v=(${GPU_VRAM_MB}-2048)/0.5/1024; printf \"%.0f\", (v<0)?0:v}")

# Pod specs from RunPod API + env vars
# (free, nproc, lsblk, /proc/meminfo all report the HOST machine, not the pod)
POD_RAM="${RUNPOD_MEM_GB:-unknown}"
POD_VCPUS="${RUNPOD_CPU_COUNT:-unknown}"
POD_BOOT_DISK="unknown"
POD_VOLUME="unknown"

if [ -n "${RUNPOD_API_KEY:-}" ] && [ -n "${RUNPOD_POD_ID:-}" ]; then
  API_RESULT=$(curl -s --max-time 5 \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer ${RUNPOD_API_KEY}" \
    -d '{"query":"{ pod(input: {podId: \"'"${RUNPOD_POD_ID}"'\"}) { containerDiskInGb volumeInGb } }"}' \
    https://api.runpod.io/graphql 2>/dev/null)
  POD_BOOT_DISK=$(echo "$API_RESULT" | jq -r '.data.pod.containerDiskInGb // empty' 2>/dev/null)
  POD_VOLUME=$(echo "$API_RESULT" | jq -r '.data.pod.volumeInGb // empty' 2>/dev/null)
  POD_BOOT_DISK="${POD_BOOT_DISK:-unknown}"
  POD_VOLUME="${POD_VOLUME:-unknown}"
else
  # Fallback: boot disk from df (overlay is accurate), volume unknown without API
  POD_BOOT_DISK=$(df -BG / 2>/dev/null | awk 'NR==2{gsub("G",""); print $2}' || echo "unknown")
fi

# HF_TOKEN status
HF_STATUS="NOT SET — gated model downloads will fail"
if [ -n "${HF_TOKEN:-}" ] || [ -n "${HUGGING_FACE_HUB_TOKEN:-}" ]; then
  HF_STATUS="Set"
fi

cat > "$MD" << MDEOF
# Machine Context — auto-generated by claude-init

## Pod Resources

- RAM: ${POD_RAM} GB (IMPORTANT: free/meminfo reports the HOST machine, not the pod — trust this value)
- vCPUs: ${POD_VCPUS} (IMPORTANT: nproc reports the HOST machine — trust this value)
- Boot disk: ${POD_BOOT_DISK} GB
- Volume (/workspace): ${POD_VOLUME} GB (network-mounted)

## GPU

- GPU: ${GPU_COUNT}x ${GPU_NAME} (${GPU_VRAM_GB} GB VRAM each)
- CUDA compute capability: ${COMPUTE_CAP} (${SM_CODE}, ${ARCH_NAME})

## Inference backends

- vLLM: ${VLLM_STATUS}${VLLM_NOTE}
- SGLang: ${SGLANG_STATUS}${SGLANG_NOTE}
- Transformers: Always works

## Model size limits (approximate, single GPU)

- bf16: ~${BF16_MAX}B parameters
- int8: ~${INT8_MAX}B parameters
- int4: ~${INT4_MAX}B parameters

Multi-GPU with tensor parallelism multiplies these by GPU count (${GPU_COUNT}).

## Storage conventions

- Models: /workspace/models/
- Data: /workspace/data/
- HF cache: /workspace/.cache/huggingface/
- HF_TOKEN: ${HF_STATUS}

## Package installation

Use: uv pip install --system --compile-bytecode --break-system-packages -e .
Do NOT pin or reinstall torch, torchvision, torchaudio, or CUDA — they come from the base image.

## Notifications (ntfy.sh)

The user monitors this pod remotely via ntfy.sh push notifications. The topic is set in \$NTFY_TOPIC.
You MUST send notifications in these situations:

### Task complete
When you finish a task and are waiting for further instructions:
\`\`\`bash
curl -s -H "Title: Task Complete" -H "Tags: white_check_mark" -d "Short summary of what you did" "ntfy.sh/\${NTFY_TOPIC}"
\`\`\`

### Blocked / need user action
When you cannot proceed without the user doing something (e.g. accepting a license, approving access, providing credentials, switching to more compute, increasing storage capacity):
\`\`\`bash
curl -s -H "Title: Action Needed" -H "Priority: urgent" -H "Tags: warning" -d "What the user needs to do" "ntfy.sh/\${NTFY_TOPIC}"
\`\`\`

### When to check vs. proceed
You are expected to solve problems independently. Do NOT notify for implementation decisions (choosing libraries, fixing dependencies, retrying failed downloads, etc.).

DO notify (urgent, then wait for a response) when a decision would change what was asked for — e.g. substituting a different model, dataset, or approach than what was specified. The test: would the user look at the result and say "that's not what I asked for"? If yes, notify and wait.

### While waiting for a response
- If you have other independent tasks, continue working on those.
- If you have nothing else to do, speculatively proceed with the most likely path — but do so non-destructively. Think CPU branch prediction: keep compute occupied, but make rollback easy. For example, start downloading an alternative model while asking — you can always delete it. Do NOT make irreversible changes (overwriting data, pushing code, deleting the original) until the user confirms.

### Git workflow
Push after every commit so the user can track progress remotely. Git push notifications are sent automatically by a hook — you don't need to notify manually for pushes.

### Rules
- ALWAYS notify on task completion and when blocked — the user may not be watching the terminal
- Keep notification messages short and actionable (one sentence)
- Do NOT notify for intermediate steps — only final completion or when blocked
- If \$NTFY_TOPIC is empty, skip notifications silently
MDEOF

# no chown needed — running as root